version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install:
    commands:
      - echo Entered the install phase...
#      - apt-get update -y
#      - apt-get install -y maven
    finally:
      - echo Completed  the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
#      - docker login -u User -p $LOGIN_PASSWORD
    finally:
      - echo Completed  the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
#      - mvn install
      - mvn clean prepare-package war:exploded
    finally:
      - echo Completed  the build phase...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - mv target/deploy ./
    finally:
      - echo Completed  the post_build phase...

#reports:
#  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
#    files:
#      - "**/*"
#    base-directory: 'target/tests/reports'
#    discard-paths: no
#  reportGroupCucumberJson:
#    files:
#      - 'cucumber/target/cucumber-tests.xml'
#    discard-paths: yes
#    file-format: CUCUMBERJSON # default is JUNITXML
artifacts:
  files:
    - echo Entered the artifacts phase...
#    - target/messageUtil-1.0.jar
    - deploy/**/*
#  discard-paths: yes
#  secondary-artifacts:
#    artifact1:
#      files:
#        - target/artifact-1.0.jar
#      discard-paths: yes
#    artifact2:
#      files:
#        - target/artifact-2.0.jar
#      discard-paths: yes
#cache:
#  paths:
#    - '/root/.m2/**/*'
  - echo Completed  the artifacts phase...
